##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [5]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


## Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
arr=np.array([1,2,3,3,4,6])
print(arr[0])
print(arr[-2])

1
4


Now lets see the 2D indexing aswell

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr[0]

array([1, 2, 3])

In [12]:
arr[1]

array([4, 5, 6])

In [14]:
arr[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

Now we can also do the slicing lets see the **slicing in 1D**

In [20]:
a=np.array([1,3,5,6,7,8,4,2,7,8])
a[1:7:2]

array([3, 6, 8])

1D slicing was really easy now lets see the **slicing in 2D**

In [22]:
arr=np.random.randint(1,15,(5,3))
arr

array([[ 9, 12,  3],
       [ 1,  3,  4],
       [12,  3,  1],
       [ 3, 14, 12],
       [14,  4,  2]], dtype=int32)

In [24]:
arr[0:2,0:2]

array([[ 9, 12],
       [ 1,  3]], dtype=int32)

In [25]:
arr[0:2,1:3]

array([[12,  3],
       [ 3,  4]], dtype=int32)

In [26]:
arr[3:5,1:3]

array([[14, 12],
       [ 4,  2]], dtype=int32)

There is one more thing known as **Boolean indexing**

In [27]:
condition=arr>10
condition

array([[False,  True, False],
       [False, False, False],
       [ True, False, False],
       [False,  True,  True],
       [ True, False, False]])

In [28]:
arr[condition]

array([12, 12, 14, 12, 14], dtype=int32)

- Boolean masking convert everything into 1D numpy array

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [30]:
np.arange(1,31).reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [32]:
a=np.arange(1,31).reshape(5,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [33]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])