# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
a=[1,2,3,4,5]
arr=np.array(a)
arr

array([1, 2, 3, 4, 5])

Lets create a matrix using list

In [4]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Now lets see how matlix looks like using numpy arrays

In [5]:
arr=np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [12]:
np.zeros((6,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
np.ones((5,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
np.full([4,5],2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [15]:
np.arange(2,50,5)

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

In [16]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(5,6)

array([[0.5669419 , 0.51694411, 0.03658393, 0.84939408, 0.18186553,
        0.93179775],
       [0.43765297, 0.53276097, 0.56968525, 0.8069499 , 0.14880802,
        0.35349757],
       [0.6867697 , 0.95536823, 0.82033613, 0.630011  , 0.31860884,
        0.86131355],
       [0.43927279, 0.89432364, 0.99510946, 0.9187583 , 0.34186067,
        0.54498155],
       [0.46715665, 0.38967831, 0.84455689, 0.21291391, 0.59815759,
        0.62611689]])

In [21]:
np.random.randint(5,31,(4,5))

array([[18,  7, 20, 24, 18],
       [26, 29, 19, 12, 22],
       [25,  9, 18, 17, 27],
       [19, 28, 28, 12, 25]], dtype=int32)

In [23]:
arr=np.random.randn(2,4)
arr

array([[-0.58888402, -0.8174497 ,  2.32989625,  1.28138411],
       [ 1.02931175,  0.4159181 ,  2.55308958, -1.3523326 ]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution