##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [1]:
import numpy as np
a=[1,2,3,4,5]
b=[5,6,7,8,9]
a+b

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]

In [5]:
a=np.array(a)
b=np.array(b)
print(a+b)
print(b-b)
print(a*b)
print(a/b)
print(b//a)

[ 6  8 10 12 14]
[0 0 0 0 0]
[ 5 12 21 32 45]
[0.2        0.33333333 0.42857143 0.5        0.55555556]
[5 3 2 2 1]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [6]:
a=np.array([1,2,3,4,5])
print(a*2)

[ 2  4  6  8 10]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [7]:
arr=np.random.randint(3,20,(3,4))
print(arr)
print(arr*4)

[[ 4 19 15 17]
 [15 12 17  8]
 [ 3 11  6  7]]
[[16 76 60 68]
 [60 48 68 32]
 [12 44 24 28]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [9]:
arr=np.random.randint(3,40,10)
arr

array([18, 36, 20, 31, 29, 21, 34, 34, 21, 13], dtype=int32)

In [10]:
print(np.mean(arr))
print(np.sum(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

25.7
257
25.0
13
36
7.6164296097318465
58.010000000000005


You can also do the axis based operations row-Wise and Colum-wise

In [13]:
data=np.random.randint(1,4,(5,6))
data

array([[2, 3, 2, 2, 2, 2],
       [2, 3, 1, 3, 1, 3],
       [3, 1, 3, 1, 3, 1],
       [1, 1, 1, 1, 1, 1],
       [3, 2, 1, 1, 3, 2]], dtype=int32)

In [16]:
print(np.sum(data,axis=0))#COLUMN WISE
print(np.mean(data,axis=0))
print(np.median(data,axis=0))
print(np.sum(data,axis=1))#ROW
print(np.mean(data,axis=1))
print(np.median(data,axis=1))

[11 10  8  8 10  9]
[2.2 2.  1.6 1.6 2.  1.8]
[2. 2. 1. 1. 2. 2.]
[13 13 12  6 12]
[2.16666667 2.16666667 2.         1.         2.        ]
[2.  2.5 2.  1.  2. ]
