##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [4]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80])
a=[1,2,3,4,5,6,7,8,9]
print(a[0])
print(arr[[0,2,7]])

1
[10 30 80]


You can do this fancy indexing in 2D Matrix aswell

In [10]:
matrix=np.arange(1,13).reshape(3,4)
print(matrix)
matrix[[0,2],[1,3]]# 1st element of 0th and 3rd element of 2nd array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 2, 12])

## Conditional Selection
Find values based on conditions or replace them.

In [11]:
arr=np.random.randint(2,33,8)
arr

array([15, 32, 31, 31, 27, 28,  6, 10], dtype=int32)

In [12]:
arr[arr<30]

array([15, 27, 28,  6, 10], dtype=int32)

In [13]:
np.where(arr<30,arr,0)

array([15,  0,  0,  0, 27, 28,  6, 10], dtype=int32)

## Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [14]:
np.sort(arr)

array([ 6, 10, 15, 27, 28, 31, 31, 32], dtype=int32)

In [15]:
np.argsort(arr)

array([6, 7, 0, 4, 5, 2, 3, 1])

## Concatenation & Stacking

In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concat([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [18]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A)
print()
print(B)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


- VERTICAL STACKING

In [19]:
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
np.vstack((B,A))

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

- HORIZONTAL STACKING

In [21]:
np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [22]:
np.hstack((B,A))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [23]:
np.concat([A,B])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])